---
- name: set up webserver
  hosts: all
  tasks:
    - name: ensure nginx is at the latest version
      apt:
        name: nginx
        state: latest
    - name: start nginx
      service:
        name: nginx
        state: started
        enabled: yes
- name: Install MariaDB, PHP, and Update Packages
  hosts: all
  become: true
  tasks:
    - name: Update all packages
      package:
        name: '*'
        state: latest
    - name: Install MariaDB Server
      apt:
        name: mariadb-server
        state: latest
    - name: Install php
      apt:
        name:
          - php
          - php-mysql1
          - php-cli
          - php-common
          - php-gd
          - php-mbstring
          - php-xml
          - php-json
        state: latest